from __future__ import annotations

from io import BytesIO
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)


def _safe_text(value: Any) -> str:
    """Convert any value into safe printable text."""
    if value is None:
        return ""
    return str(value).strip()


def _bullet_list(items: list[str]) -> list:
    """Build ReportLab bullet paragraphs."""
    styles = getSampleStyleSheet()
    bullet_style = ParagraphStyle(
        "Bullet",
        parent=styles["BodyText"],
        fontSize=10,
        leading=14,
        leftIndent=12,
    )

    if not items:
        return [Paragraph("- No items available.", bullet_style)]

    return [Paragraph(f"- {_safe_text(item)}", bullet_style) for item in items]


def build_analysis_pdf_report(
    *,
    cv_filename: str,
    score: int,
    summary: str,
    strengths: list[str],
    weaknesses: list[str],
    recommendations: list[str],
    job_description: str,
) -> bytes:
    """Generate a branded TalentMatch Pro analysis PDF report."""
    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=1.6 * cm,
        leftMargin=1.6 * cm,
        topMargin=1.6 * cm,
        bottomMargin=1.6 * cm,
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "TitleStyle",
        parent=styles["Title"],
        fontSize=22,
        leading=28,
        textColor=colors.HexColor("#111827"),
        spaceAfter=12,
    )

    subtitle_style = ParagraphStyle(
        "SubtitleStyle",
        parent=styles["BodyText"],
        fontSize=11,
        leading=15,
        textColor=colors.HexColor("#4B5563"),
        spaceAfter=14,
    )

    section_style = ParagraphStyle(
        "SectionStyle",
        parent=styles["Heading2"],
        fontSize=14,
        leading=18,
        textColor=colors.HexColor("#111827"),
        spaceBefore=14,
        spaceAfter=8,
    )

    body_style = ParagraphStyle(
        "BodyStyle",
        parent=styles["BodyText"],
        fontSize=10,
        leading=14,
        textColor=colors.HexColor("#111827"),
    )

    story = []

    story.append(Paragraph("TalentMatch Pro - CV Analysis Report", title_style))
    story.append(
        Paragraph(
            "AI-powered CV matching report generated from your CV and target job description.",
            subtitle_style,
        )
    )

    score_table = Table(
        [
            ["CV File", _safe_text(cv_filename)],
            ["Match Score", f"{score}/100"],
        ],
        colWidths=[4 * cm, 11 * cm],
    )

    score_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#EEF2FF")),
                ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#111827")),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#D1D5DB")),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("PADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )

    story.append(score_table)
    story.append(Spacer(1, 10))

    story.append(Paragraph("Summary", section_style))
    story.append(Paragraph(_safe_text(summary), body_style))

    story.append(Paragraph("Strengths", section_style))
    story.extend(_bullet_list(strengths))

    story.append(Paragraph("Missing Skills", section_style))
    story.extend(_bullet_list(weaknesses))

    story.append(Paragraph("Recommendations", section_style))
    story.extend(_bullet_list(recommendations))

    story.append(Paragraph("Job Description", section_style))
    story.append(Paragraph(_safe_text(job_description), body_style))

    story.append(Spacer(1, 18))
    story.append(
        Paragraph(
            "Generated by TalentMatch Pro",
            ParagraphStyle(
                "Footer",
                parent=styles["BodyText"],
                fontSize=9,
                textColor=colors.HexColor("#6B7280"),
            ),
        )
    )

    doc.build(story)

    pdf_bytes = buffer.getvalue()
    buffer.close()

    return pdf_bytes